"""
Localization resources.
Contains string translations for supported languages.
"""

LANGUAGES = {
    "en": {
        "live_title": "IVAO {country} Live - {date}",
        "daily_title": "Daily Report IVAO {country} - {date}",
        "weekly_title": "Weekly Report IVAO {country} - Week {week} {year}",
        "monthly_title": "Monthly Report IVAO {country} - {date}",
        "domestic_flights": "{flag} Domestic Flights",
        "intl_arrivals": "{world} Int'l (Arrivals)",
        "intl_departures": "{world} Int'l (Departures)",
        "pilots_online": "👨‍✈️ Pilots Online",
        "flight_hours": "⏱️ Flight Hours",
        "controllers": "📡 Controllers",
        "status_no_atc": "No ATC Online 😴",
        "controlling": "🎙️ Controlling",
        "flying": "✈️ Flying",
        "total_flights": "✈️ Total Flights",
        "pilots": "👨‍✈️ Pilots",
        "footer": "International Virtual Aviation Organisation {heart} - @746048",
        "metar": "{emoji} METAR {airport}",
        "presence_pilot": "Pilot",
        "presence_pilots": "Pilots",
        "presence_atc": "ATC",
        "presence_atcs": "ATCs",
        "presence_online": "Online!",
        "status_title": "🔴 Status",
        "next_event_label": "Next Event"
    },
    "es": {
        "live_title": "IVAO {country} En Vivo - {date}",
        "daily_title": "Reporte Diario IVAO {country} - {date}",
        "weekly_title": "Reporte Semanal IVAO {country} - Semana {week} {year}",
        "monthly_title": "Reporte Mensual IVAO {country} - {date}",
        "domestic_flights": "{flag} Vuelos Locales",
        "intl_arrivals": "{world} Int'l (Llegadas)",
        "intl_departures": "{world} Int'l (Salidas)",
        "pilots_online": "👨‍✈️ Pilotos Online",
        "flight_hours": "⏱️ Horas de Vuelo",
        "controllers": "📡 Controladores",
        "status_no_atc": "Sin ATC Online 😴",
        "controlling": "🎙️ Controlando",
        "flying": "✈️ Volando",
        "total_flights": "✈️ Vuelos Totales",
        "pilots": "👨‍✈️ Pilotos",
        "footer": "International Virtual Aviation Organisation {heart} - @746048",
        "metar": "{emoji} METAR {airport}",
        "presence_pilot": "Piloto",
        "presence_pilots": "Pilotos",
        "presence_atc": "ATC",
        "presence_atcs": "ATCs",
        "presence_online": "En Línea!",
        "status_title": "🔴 Estado",
        "next_event_label": "Próximo Evento"
    },
    "pt": {
        "live_title": "IVAO {country} Ao Vivo - {date}",
        "daily_title": "Relatório Diário IVAO {country} - {date}",
        "weekly_title": "Relatório Semanal IVAO {country} - Semana {week} {year}",
        "monthly_title": "Relatório Mensal IVAO {country} - {date}",
        "domestic_flights": "{flag} Voos Domésticos",
        "intl_arrivals": "{world} Int'l (Chegadas)",
        "intl_departures": "{world} Int'l (Partidas)",
        "pilots_online": "👨‍✈️ Pilotos Online",
        "flight_hours": "⏱️ Horas de Voo",
        "controllers": "📡 Controladores",
        "status_no_atc": "Sem ATC Online 😴",
        "controlling": "🎙️ Controlando",
        "flying": "✈️ Voando",
        "total_flights": "✈️ Total de Voos",
        "pilots": "👨‍✈️ Pilotos",
        "footer": "International Virtual Aviation Organisation {heart} - @746048",
        "metar": "{emoji} METAR {airport}",
        "presence_pilot": "Piloto",
        "presence_pilots": "Pilotos",
        "presence_atc": "ATC",
        "presence_atcs": "ATCs",
        "presence_online": "Online!",
        "status_title": "🔴 Estado",
        "next_event_label": "Próximo Evento"
    },
    "fr": {
        "live_title": "IVAO {country} En Direct - {date}",
        "daily_title": "Rapport Quotidien IVAO {country} - {date}",
        "weekly_title": "Rapport Hebdomadaire IVAO {country} - Semaine {week} {year}",
        "monthly_title": "Rapport Mensuel IVAO {country} - {date}",
        "domestic_flights": "{flag} Vols Locaux",
        "intl_arrivals": "{world} Int'l (Arrivées)",
        "intl_departures": "{world} Int'l (Départs)",
        "pilots_online": "👨‍✈️ Pilotes en Ligne",
        "flight_hours": "⏱️ Heures de Vol",
        "controllers": "📡 Contrôleurs",
        "status_no_atc": "No ATC Online 😴",
        "controlling": "🎙️ Contrôle",
        "flying": "✈️ En Vol",
        "total_flights": "✈️ Total des Vols",
        "pilots": "👨‍✈️ Pilotes",
        "footer": "International Virtual Aviation Organisation {heart} - @746048",
        "metar": "{emoji} METAR {airport}",
        "presence_pilot": "Pilote",
        "presence_pilots": "Pilotes",
        "presence_atc": "ATC",
        "presence_atcs": "ATCs",
        "presence_online": "En Ligne!",
        "status_title": "🔴 Statut",
        "next_event_label": "Prochain Événement"
    },
    "de": {
        "live_title": "IVAO {country} Live - {date}",
        "daily_title": "Tagesbericht IVAO {country} - {date}",
        "weekly_title": "Wochenbericht IVAO {country} - Woche {week} {year}",
        "monthly_title": "Monatsbericht IVAO {country} - {date}",
        "domestic_flights": "{flag} Inlandsflüge",
        "intl_arrivals": "{world} Int'l (Ankünfte)",
        "intl_departures": "{world} Int'l (Abflüge)",
        "pilots_online": "👨‍✈️ Piloten Online",
        "flight_hours": "⏱️ Flugstunden",
        "controllers": "📡 Fluglotsen",
        "status_no_atc": "No ATC Online 😴",
        "controlling": "🎙️ Dienst",
        "flying": "✈️ Fliegend",
        "total_flights": "✈️ Flüge Gesamt",
        "pilots": "👨‍✈️ Piloten",
        "footer": "International Virtual Aviation Organisation {heart} - @746048",
        "metar": "{emoji} METAR {airport}",
        "presence_pilot": "Pilot",
        "presence_pilots": "Piloten",
        "presence_atc": "ATC",
        "presence_atcs": "ATCs",
        "presence_online": "Online!",
        "status_title": "🔴 Status",
        "next_event_label": "Nächstes Event"
    },
    "it": {
        "live_title": "IVAO {country} Live - {date}",
        "daily_title": "Rapporto Giornaliero IVAO {country} - {date}",
        "weekly_title": "Rapporto Settimanale IVAO {country} - Settimana {week} {year}",
        "monthly_title": "Rapporto Mensile IVAO {country} - {date}",
        "domestic_flights": "{flag} Voli Nazionali",
        "intl_arrivals": "{world} Int'l (Arrivi)",
        "intl_departures": "{world} Int'l (Partenze)",
        "pilots_online": "👨‍✈️ Piloti Online",
        "flight_hours": "⏱️ Ore di Volo",
        "controllers": "📡 Controllori",
        "status_no_atc": "No ATC Online 😴",
        "controlling": "🎙️ Controllo",
        "flying": "✈️ In Volo",
        "total_flights": "✈️ Voli Totali",
        "pilots": "👨‍✈️ Piloti",
        "footer": "International Virtual Aviation Organisation {heart} - @746048",
        "metar": "{emoji} METAR {airport}",
        "presence_pilot": "Pilota",
        "presence_pilots": "Piloti",
        "presence_atc": "ATC",
        "presence_atcs": "ATCs",
        "presence_online": "Online!",
        "status_title": "🔴 Stato",
        "next_event_label": "Prossimo Evento"
    },
    "nl": {
        "live_title": "IVAO {country} Live - {date}",
        "daily_title": "Dagelijks Rapport IVAO {country} - {date}",
        "weekly_title": "Wekelijks Rapport IVAO {country} - Week {week} {year}",
        "monthly_title": "Maandelijks Rapport IVAO {country} - {date}",
        "domestic_flights": "{flag} Binnenlandse Vluchten",
        "intl_arrivals": "{world} Int'l (Aankomst)",
        "intl_departures": "{world} Int'l (Vertrek)",
        "pilots_online": "👨‍✈️ Piloten Online",
        "flight_hours": "⏱️ Vlieguren",
        "controllers": "📡 Verkeersleiders",
        "status_no_atc": "No ATC Online 😴",
        "controlling": "🎙️ Dienst",
        "flying": "✈️ Vliegend",
        "total_flights": "✈️ Totaal Vluchten",
        "pilots": "👨‍✈️ Piloten",
        "footer": "International Virtual Aviation Organisation {heart} - @746048",
        "metar": "{emoji} METAR {airport}",
        "presence_pilot": "Piloot",
        "presence_pilots": "Piloten",
        "presence_atc": "ATC",
        "presence_atcs": "ATCs",
        "presence_online": "Online!",
        "status_title": "🔴 Status",
        "next_event_label": "Volgend Event"
    },
    "tr": {
        "live_title": "IVAO {country} Canlı - {date}",
        "daily_title": "Günlük Rapor IVAO {country} - {date}",
        "weekly_title": "Haftalık Rapor IVAO {country} - Hafta {week} {year}",
        "monthly_title": "Aylık Rapor IVAO {country} - {date}",
        "domestic_flights": "{flag} İç Hatlar",
        "intl_arrivals": "{world} Dış Hatlar (Geliş)",
        "intl_departures": "{world} Dış Hatlar (Gidiş)",
        "pilots_online": "👨‍✈️ Çevrimiçi Pilotlar",
        "flight_hours": "⏱️ Uçuş Saatleri",
        "controllers": "📡 Kontrolörler",
        "status_no_atc": "No ATC Online 😴",
        "controlling": "🎙️ Kontrol",
        "flying": "✈️ Uçuşta",
        "total_flights": "✈️ Toplam Uçuşlar",
        "pilots": "👨‍✈️ Pilotlar",
        "footer": "International Virtual Aviation Organisation {heart} - @746048",
        "metar": "{emoji} METAR {airport}",
        "presence_pilot": "Pilot",
        "presence_pilots": "Pilotlar",
        "presence_atc": "ATC",
        "presence_atcs": "ATC",
        "presence_online": "Çevrimiçi!",
        "status_title": "🔴 Durum",
        "next_event_label": "Sonraki Etkinlik"
    },
    "pl": {
        "live_title": "IVAO {country} Na Żywo - {date}",
        "daily_title": "Raport Dzienny IVAO {country} - {date}",
        "weekly_title": "Raport Tygodniowy IVAO {country} - Tydzień {week} {year}",
        "monthly_title": "Raport Miesięczny IVAO {country} - {date}",
        "domestic_flights": "{flag} Loty Krajowe",
        "intl_arrivals": "{world} Międzynar. (Przyloty)",
        "intl_departures": "{world} Międzynar. (Odloty)",
        "pilots_online": "👨‍✈️ Piloci Online",
        "flight_hours": "⏱️ Godziny Lotu",
        "controllers": "📡 Kontrolerzy",
        "status_no_atc": "No ATC Online 😴",
        "controlling": "🎙️ Służba",
        "flying": "✈️ W Locie",
        "total_flights": "✈️ Wszystkie Loty",
        "pilots": "👨‍✈️ Piloci",
        "footer": "International Virtual Aviation Organisation {heart} - @746048",
        "metar": "{emoji} METAR {airport}",
        "presence_pilot": "Pilot",
        "presence_pilots": "Piloci",
        "presence_atc": "ATC",
        "presence_atcs": "ATC",
        "presence_online": "Online!",
        "status_title": "🔴 Status",
        "next_event_label": "Następne Wydarzenie"
    },
     "ru": {
        "live_title": "IVAO {country} В Эфире - {date}",
        "daily_title": "Ежедневный Отчет IVAO {country} - {date}",
        "weekly_title": "Еженедельный Отчет IVAO {country} - Неделя {week} {year}",
        "monthly_title": "Ежемесячный Отчет IVAO {country} - {date}",
        "domestic_flights": "{flag} Внутренние Рейсы",
        "intl_arrivals": "{world} Межд. (Прибытие)",
        "intl_departures": "{world} Межд. (Отправление)",
        "pilots_online": "👨‍✈️ Пилоты Онлайн",
        "flight_hours": "⏱️ Часы Налета",
        "controllers": "📡 Диспетчеры",
        "status_no_atc": "No ATC Online 😴",
        "controlling": "🎙️ Контроль",
        "flying": "✈️ В Полете",
        "total_flights": "✈️ Всего Рейсов",
        "pilots": "👨‍✈️ Пилоты",
        "footer": "International Virtual Aviation Organisation {heart} - @746048",
        "metar": "{emoji} METAR {airport}",
        "presence_pilot": "Пилот",
        "presence_pilots": "Пилоты",
        "presence_atc": "Диспетчер",
        "presence_atcs": "Диспетчеры",
        "presence_online": "В сети!",
        "status_title": "🔴 Статус",
        "next_event_label": "Следующее Событие"
    },
    "id": {
        "live_title": "IVAO {country} Langsung - {date}",
        "daily_title": "Laporan Harian IVAO {country} - {date}",
        "weekly_title": "Laporan Mingguan IVAO {country} - Minggu {week} {year}",
        "monthly_title": "Laporan Bulanan IVAO {country} - {date}",
        "domestic_flights": "{flag} Penerbangan Domestik",
        "intl_arrivals": "{world} Int'l (Kedatangan)",
        "intl_departures": "{world} Int'l (Keberangkatan)",
        "pilots_online": "👨‍✈️ Pilot Online",
        "flight_hours": "⏱️ Jam Terbang",
        "controllers": "📡 Pengendali",
        "status_no_atc": "No ATC Online 😴",
        "controlling": "🎙️ Mengontrol",
        "flying": "✈️ Terbang",
        "total_flights": "✈️ Total Penerbangan",
        "pilots": "👨‍✈️ Pilot",
        "footer": "International Virtual Aviation Organisation {heart} - @746048",
        "metar": "{emoji} METAR {airport}",
        "presence_pilot": "Pilot",
        "presence_pilots": "Pilot",
        "presence_atc": "ATC",
        "presence_atcs": "ATC",
        "presence_online": "Online!",
        "status_title": "🔴 Status",
        "next_event_label": "Acara Berikutnya"
    },
    "el": {
        "live_title": "IVAO {country} Live - {date}",
        "daily_title": "Ημερήσια Αναφορά IVAO {country} - {date}",
        "weekly_title": "Εβδομαδιαία Αναφορά IVAO {country} - Εβδομάδα {week} {year}",
        "monthly_title": "Μηνιαία Αναφορά IVAO {country} - {date}",
        "domestic_flights": "{flag} Πτήσεις Εσωτερικού",
        "intl_arrivals": "{world} Διεθνείς (Αφίξεις)",
        "intl_departures": "{world} Διεθνείς (Αναχωρήσεις)",
        "pilots_online": "👨‍✈️ Πιλότοι Online",
        "flight_hours": "⏱️ Ώρες Πτήσης",
        "controllers": "📡 Ελεγκτές",
        "status_no_atc": "No ATC Online 😴",
        "controlling": "🎙️ Έλεγχος",
        "flying": "✈️ Πτήση",
        "total_flights": "✈️ Σύνολο Πτήσεων",
        "pilots": "👨‍✈️ Πιλότοι",
        "footer": "International Virtual Aviation Organisation {heart} - @746048",
        "metar": "{emoji} METAR {airport}",
        "presence_pilot": "Πιλότος",
        "presence_pilots": "Πιλότοι",
        "presence_atc": "ATC",
        "presence_atcs": "ATC",
        "presence_online": "Online!",
        "status_title": "🔴 Κατάσταση",
        "next_event_label": "Επόμενο Γεγονός"
    },
    "ro": {
        "live_title": "IVAO {country} Live - {date}",
        "daily_title": "Raport Zilnic IVAO {country} - {date}",
        "weekly_title": "Raport Săptămânal IVAO {country} - Săptămâna {week} {year}",
        "monthly_title": "Raport Lunar IVAO {country} - {date}",
        "domestic_flights": "{flag} Zboruri Interne",
        "intl_arrivals": "{world} Int'l (Sosiri)",
        "intl_departures": "{world} Int'l (Plecări)",
        "pilots_online": "👨‍✈️ Piloți Online",
        "flight_hours": "⏱️ Ore de Zbor",
        "controllers": "📡 Controlori",
        "status_no_atc": "No ATC Online 😴",
        "controlling": "🎙️ Control",
        "flying": "✈️ În Zbor",
        "total_flights": "✈️ Total Zboruri",
        "pilots": "👨‍✈️ Piloți",
        "footer": "International Virtual Aviation Organisation {heart} - @746048",
        "metar": "{emoji} METAR {airport}",
        "presence_pilot": "Pilot",
        "presence_pilots": "Piloți",
        "presence_atc": "ATC",
        "presence_atcs": "ATC",
        "presence_online": "Online!",
        "status_title": "🔴 Status",
        "next_event_label": "Următorul Eveniment"
    },
    "hu": {
        "live_title": "IVAO {country} Élő - {date}",
        "daily_title": "Napi Jelentés IVAO {country} - {date}",
        "weekly_title": "Heti Jelentés IVAO {country} - {week}. Hét {year}",
        "monthly_title": "Havi Jelentés IVAO {country} - {date}",
        "domestic_flights": "{flag} Belföldi Járatok",
        "intl_arrivals": "{world} Nemzetközi (Érkező)",
        "intl_departures": "{world} Nemzetközi (Induló)",
        "pilots_online": "👨‍✈️ Pilóták Online",
        "flight_hours": "⏱️ Repült Órák",
        "controllers": "📡 Irányítók",
        "status_no_atc": "No ATC Online 😴",
        "controlling": "🎙️ Irányítás",
        "flying": "✈️ Repül",
        "total_flights": "✈️ Összes Járat",
        "pilots": "👨‍✈️ Pilóták",
        "footer": "International Virtual Aviation Organisation {heart} - @746048",
        "metar": "{emoji} METAR {airport}",
        "presence_pilot": "Pilóta",
        "presence_pilots": "Pilóta",
        "presence_atc": "Irányító",
        "presence_atcs": "Irányító",
        "presence_online": "Online!",
        "status_title": "🔴 Állapot",
        "next_event_label": "Következő Esemény"
    },
    "cs": {
        "live_title": "IVAO {country} Živě - {date}",
        "daily_title": "Denní Hlášení IVAO {country} - {date}",
        "weekly_title": "Týdenní Hlášení IVAO {country} - Týden {week} {year}",
        "monthly_title": "Měsíční Hlášení IVAO {country} - {date}",
        "domestic_flights": "{flag} Vnitrostátní Lety",
        "intl_arrivals": "{world} Mezinár. (Přílety)",
        "intl_departures": "{world} Mezinár. (Odlety)",
        "pilots_online": "👨‍✈️ Piloti Online",
        "flight_hours": "⏱️ Letové Hodiny",
        "controllers": "📡 Řídící",
        "status_no_atc": "No ATC Online 😴",
        "controlling": "🎙️ Řízení",
        "flying": "✈️ Letí",
        "total_flights": "✈️ Celkem Letů",
        "pilots": "👨‍✈️ Piloti",
        "footer": "International Virtual Aviation Organisation {heart} - @746048",
        "metar": "{emoji} METAR {airport}",
        "presence_pilot": "Pilot",
        "presence_pilots": "Piloti",
        "presence_atc": "Řídící",
        "presence_atcs": "Řídící",
        "presence_online": "Online!",
        "status_title": "🔴 Stav",
        "next_event_label": "Další Událost"
    },
    "uk": {
        "live_title": "IVAO {country} Наживо - {date}",
        "daily_title": "Щоденний Звіт IVAO {country} - {date}",
        "weekly_title": "Тижневий Звіт IVAO {country} - Тиждень {week} {year}",
        "monthly_title": "Місячний Звіт IVAO {country} - {date}",
        "domestic_flights": "{flag} Внутрішні Рейси",
        "intl_arrivals": "{world} Міжнар. (Прибуття)",
        "intl_departures": "{world} Міжнар. (Відправлення)",
        "pilots_online": "👨‍✈️ Пілоти Онлайн",
        "flight_hours": "⏱️ Години Польоту",
        "controllers": "📡 Диспетчери",
        "status_no_atc": "No ATC Online 😴",
        "controlling": "🎙️ Контроль",
        "flying": "✈️ У Польоті",
        "total_flights": "✈️ Всього Рейсів",
        "pilots": "👨‍✈️ Пілоти",
        "footer": "International Virtual Aviation Organisation {heart} - @746048",
        "metar": "{emoji} METAR {airport}",
        "presence_pilot": "Пілот",
        "presence_pilots": "Пілоти",
        "presence_atc": "ATC",
        "presence_atcs": "ATC",
        "presence_online": "Онлайн!",
        "status_title": "🔴 Статус",
        "next_event_label": "Наступна Подія"
    },
    "ar": {
        "live_title": "IVAO {country} مباشر - {date}",
        "daily_title": "التقرير اليومي IVAO {country} - {date}",
        "weekly_title": "التقرير الاسبوعي IVAO {country} - الاسبوع {week} {year}",
        "monthly_title": "التقرير الشهري IVAO {country} - {date}",
        "domestic_flights": "{flag} رحلات داخلية",
        "intl_arrivals": "{world} دولي (وصول)",
        "intl_departures": "{world} دولي (مغادرة)",
        "pilots_online": "👨‍✈️ طيارين متصلين",
        "flight_hours": "⏱️ ساعات الطيران",
        "controllers": "📡 مراقبين جويين",
        "status_no_atc": "No ATC Online 😴",
        "controlling": "🎙️ مراقبة",
        "flying": "✈️ طيران",
        "total_flights": "✈️ مجموع الرحلات",
        "pilots": "👨‍✈️ الطيارين",
        "footer": "International Virtual Aviation Organisation {heart} - @746048",
        "metar": "{emoji} METAR {airport}",
        "presence_pilot": "طيار",
        "presence_pilots": "طيارون",
        "presence_atc": "مراقب",
        "presence_atcs": "مراقبون",
        "presence_online": "متصل!",
        "status_title": "🔴 الحالة",
        "next_event_label": "الحدث القادم"
    },
    "zh": {
        "live_title": "IVAO {country} 实时 - {date}",
        "daily_title": "IVAO {country} 日报 - {date}",
        "weekly_title": "IVAO {country} 周报 - 第 {week} 周 {year}",
        "monthly_title": "IVAO {country} 月报 - {date}",
        "domestic_flights": "{flag} 国内航班",
        "intl_arrivals": "{world} 国际 (抵达)",
        "intl_departures": "{world} 国际 (出发)",
        "pilots_online": "👨‍✈️ 在线飞行员",
        "flight_hours": "⏱️ 飞行时数",
        "controllers": "📡 管制员",
        "status_no_atc": "No ATC Online 😴",
        "controlling": "🎙️ 管制中",
        "flying": "✈️ 飞行中",
        "total_flights": "✈️ 总航班数",
        "pilots": "👨‍✈️ 飞行员",
        "footer": "International Virtual Aviation Organisation {heart} - @746048",
        "metar": "{emoji} METAR {airport}",
        "presence_pilot": "飞行员",
        "presence_pilots": "飞行员",
        "presence_atc": "管制员",
        "presence_atcs": "管制员",
        "presence_online": "在线!",
        "status_title": "🔴 状态",
        "next_event_label": "下一个活动"
    }
}

def get_text(lang_code: str, key: str, **kwargs) -> str:
    """
    Get translated text for key and language code.
    Falls back to 'en' if language or key not found.
    Allows string formatting via kwargs.
    """
    # Normalize language code (e.g. pt-BR -> pt)
    lang = lang_code.split('-')[0].lower()
    
    # Get dictionary for language, fallback to en
    resources = LANGUAGES.get(lang, LANGUAGES.get("en", {}))
    
    # Get string, fallback to en if key missing in target language
    text = resources.get(key)
    if text is None:
        text = LANGUAGES["en"].get(key, key)
    
    # Format if arguments provided
    if kwargs:
        try:
            text = text.format(**kwargs)
        except KeyError:
            pass
            
    if lang == 'ar':
        text = '\u202A' + text + '\u202C'
        
    return text
